#Importing required modules#

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the required data set (CSV files)#

In [4]:
df_train=pd.read_csv("train_data_evaluation_part_2.csv")
df_test=pd.read_csv("test_data_evaluation_part2.csv")
df_train.head(10)
df_test.head(10)

,Unnamed: 0,ID,Nationality,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,82590,82591,SGP,47.0,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,82591,82592,SGP,16.0,11,130,483.48,155.1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,82592,82593,SGP,15.0,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,82593,82594,SGP,12.0,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,82594,82595,PRT,NaN,11,0,0.00,0.0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,82595,82596,PRT,42.0,11,1,59.00,7.0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,82596,82597,PER,31.0,11,4,142.40,33.0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,82597,82598,PRT,60.0,11,0,79.00,17.0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,82598,82599,PRT,63.0,11,20,69.66,222.8,0,0,...,0,0,0,0,0,0,0,0,0,0
9,82599,82600,PRT,NaN,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0

Understanding the data

In [5]:
df_train.columns

Index(['Unnamed: 0', 'ID', 'Nationality', 'Age', 'DaysSinceCreation',
       'AverageLeadTime', 'LodgingRevenue', 'OtherRevenue', 'BookingsCanceled',
       'BookingsNoShowed', 'BookingsCheckedIn', 'PersonsNights', 'RoomNights',
       'DaysSinceLastStay', 'DaysSinceFirstStay', 'DistributionChannel',
       'MarketSegment', 'SRHighFloor', 'SRLowFloor', 'SRAccessibleRoom',
       'SRMediumFloor', 'SRBathtub', 'SRShower', 'SRCrib', 'SRKingSizeBed',
       'SRTwinBed', 'SRNearElevator', 'SRAwayFromElevator',
       'SRNoAlcoholInMiniBar', 'SRQuietRoom'],
      dtype='object')

In [6]:
df_test.columns

Index(['Unnamed: 0', 'ID', 'Nationality', 'Age', 'DaysSinceCreation',
       'AverageLeadTime', 'LodgingRevenue', 'OtherRevenue', 'BookingsCanceled',
       'BookingsNoShowed', 'BookingsCheckedIn', 'PersonsNights', 'RoomNights',
       'DaysSinceLastStay', 'DaysSinceFirstStay', 'DistributionChannel',
       'MarketSegment', 'SRHighFloor', 'SRLowFloor', 'SRAccessibleRoom',
       'SRMediumFloor', 'SRBathtub', 'SRShower', 'SRCrib', 'SRKingSizeBed',
       'SRTwinBed', 'SRNearElevator', 'SRAwayFromElevator',
       'SRNoAlcoholInMiniBar', 'SRQuietRoom'],
      dtype='object')

In [7]:
df_train.describe()

,Unnamed: 0,ID,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,BookingsCheckedIn,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
count,82580.000000,82580.000000,78834.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,...,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000,82580.000000
mean,41289.500000,41290.500000,45.468554,459.138157,66.557205,300.457373,67.890023,0.002047,0.000642,0.798402,...,0.000884,0.002809,0.001732,0.012812,0.351671,0.142771,0.000303,0.003548,0.000121,0.088060
std,23838.936952,23838.936952,16.526276,311.309295,87.928995,373.337007,114.496223,0.067177,0.029725,0.696880,...,0.029719,0.052930,0.041577,0.112463,0.477495,0.349841,0.017397,0.059460,0.011004,0.283384
min,0.000000,1.000000,-11.000000,12.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20644.750000,20645.750000,34.000000,183.000000,0.000000,66.400000,2.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,41289.500000,41290.500000,46.000000,406.000000,30.000000,234.000000,39.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,61934.250000,61935.250000,57.000000,728.000000,104.000000,403.800000,88.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,82579.000000,82580.000000,122.000000,1095.000000,588.000000,21781.000000,7730.250000,9.000000,3.000000,66.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df_test.describe()

,Unnamed: 0,ID,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,BookingsCheckedIn,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
count,1000.000000,1000.000000,967.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0,1000.0,1000.000000,...,1000.0,1000.000000,1000.0,1000.000000,1000.000000,1000.000000,1000.000000,1000.0,1000.0,1000.000000
mean,83089.500000,83090.500000,39.720786,4.100000,36.840000,163.522530,42.612590,0.0,0.0,0.485000,...,0.0,0.006000,0.0,0.047000,0.440000,0.125000,0.003000,0.0,0.0,0.115000
std,288.819436,288.819436,19.161205,3.124702,66.375508,302.384328,96.491848,0.0,0.0,0.511896,...,0.0,0.077266,0.0,0.211745,0.496635,0.330884,0.054717,0.0,0.0,0.319182
min,82590.000000,82591.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
25%,82839.750000,82840.750000,25.000000,2.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
50%,83089.500000,83090.500000,42.000000,3.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
75%,83339.250000,83340.250000,53.000000,6.000000,41.250000,252.000000,42.000000,0.0,0.0,1.000000,...,0.0,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.000000
max,83589.000000,83590.000000,90.000000,11.000000,340.000000,3104.000000,1139.500000,0.0,0.0,2.000000,...,0.0,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000

In [9]:
df_train.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82580 entries, 0 to 82579
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            82580 non-null  int64
 1   ID                    82580 non-null  int64
 2   Nationality           82580 non-null  object
 3   Age                   78834 non-null  float64
 4   DaysSinceCreation     82580 non-null  int64
 5   AverageLeadTime       82580 non-null  int64
 6   LodgingRevenue        82580 non-null  float64
 7   OtherRevenue          82580 non-null  float64
 8   BookingsCanceled      82580 non-null  int64
 9   BookingsNoShowed      82580 non-null  int64
 10  BookingsCheckedIn     82580 non-null  int64
 11  PersonsNights         82580 non-null  int64
 12  RoomNights            82580 non-null  int64
 13  DaysSinceLastStay     82580 non-null  int64
 14  DaysSinceFirstStay    82580 non-null  int64
 15  DistributionChannel   82580 non-null  object
 16  MarketSegment         82580 non-null  object
 17  SRHighFloor           82580 non-null  int64
 18  SRLowFloor            82580 non-null  int64
 19  SRAccessibleRoom      82580 non-null  int64
 20  SRMediumFloor         82580 non-null  int64
 21  SRBathtub             82580 non-null  int64
 22  SRShower              82580 non-null  int64
 23  SRCrib                82580 non-null  int64
 24  SRKingSizeBed         82580 non-null  int64
 25  SRTwinBed             82580 non-null  int64
 26  SRNearElevator        82580 non-null  int64
 27  SRAwayFromElevator    82580 non-null  int64
 28  SRNoAlcoholInMiniBar  82580 non-null  int64
 29  SRQuietRoom           82580 non-null  int64
dtypes: float64(3), int64(24), object(3)
memory usage: 18.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            1000 non-null   int64
 1   ID                    1000 non-null   int64
 2   Nationality           1000 non-null   object
 3   Age                   967 non-null    float64
 4   DaysSinceCreation     1000 non-null   int64
 5   AverageLeadTime       1000 non-null   int64
 6   LodgingRevenue        1000 non-null   float64
 7   OtherRevenue          1000 non-null   float64
 8   BookingsCanceled      1000 non-null   int64
 9   BookingsNoShowed      1000 non-null   int64
 10  BookingsCheckedIn     1000 non-null   int64
 11  PersonsNights         1000 non-null   int64
 12  RoomNights            1000 non-null   int64
 13  DaysSinceLastStay     1000 non-null   int64
 14  DaysSinceFirstStay    1000 non-null   int64
 15  DistributionChannel   1000 non-null   object
 16  MarketSegment         1000 non-null   object
 17  SRHighFloor           1000 non-null   int64
 18  SRLowFloor            1000 non-null   int64
 19  SRAccessibleRoom      1000 non-null   int64
 20  SRMediumFloor         1000 non-null   int64
 21  SRBathtub             1000 non-null   int64
 22  SRShower              1000 non-null   int64
 23  SRCrib                1000 non-null   int64
 24  SRKingSizeBed         1000 non-null   int64
 25  SRTwinBed             1000 non-null   int64
 26  SRNearElevator        1000 non-null   int64
 27  SRAwayFromElevator    1000 non-null   int64
 28  SRNoAlcoholInMiniBar  1000 non-null   int64
 29  SRQuietRoom           1000 non-null   int64
dtypes: float64(3), int64(24), object(3)
memory usage: 234.5+ KB

#Imputing the missing values in the data set#

In [10]:
df_train.isnull().sum()
df_test.isnull().sum()

Unnamed: 0               0
ID                       0
Nationality              0
Age                     33
DaysSinceCreation        0
AverageLeadTime          0
LodgingRevenue           0
OtherRevenue             0
BookingsCanceled         0
BookingsNoShowed         0
BookingsCheckedIn        0
PersonsNights            0
RoomNights               0
DaysSinceLastStay        0
DaysSinceFirstStay       0
DistributionChannel      0
MarketSegment            0
SRHighFloor              0
SRLowFloor               0
SRAccessibleRoom         0
SRMediumFloor            0
SRBathtub                0
SRShower                 0
SRCrib                   0
SRKingSizeBed            0
SRTwinBed                0
SRNearElevator           0
SRAwayFromElevator       0
SRNoAlcoholInMiniBar     0
SRQuietRoom              0
dtype: int64

Finding the mode of Age column

In [11]:
print(df_train['Age'].mode())
print(df_test['Age'].mode())

0    50.0
dtype: float64
0    46.0
dtype: float64

Imputing the missing vlaue in the column "Age"

In [12]:
missing_col =['Age']

#Using mode of the age calculated before to impute the missing values
for i in missing_col:
  df_train.loc[df_train.loc[:,i].isnull(),i] = 50
  df_test.loc[df_test.loc[:,i].isnull(),i] = 46

In [13]:
df_train.isnull().sum()
df_test.isnull().sum()

Unnamed: 0              0
ID                      0
Nationality             0
Age                     0
DaysSinceCreation       0
AverageLeadTime         0
LodgingRevenue          0
OtherRevenue            0
BookingsCanceled        0
BookingsNoShowed        0
BookingsCheckedIn       0
PersonsNights           0
RoomNights              0
DaysSinceLastStay       0
DaysSinceFirstStay      0
DistributionChannel     0
MarketSegment           0
SRHighFloor             0
SRLowFloor              0
SRAccessibleRoom        0
SRMediumFloor           0
SRBathtub               0
SRShower                0
SRCrib                  0
SRKingSizeBed           0
SRTwinBed               0
SRNearElevator          0
SRAwayFromElevator      0
SRNoAlcoholInMiniBar    0
SRQuietRoom             0
dtype: int64

In [14]:
print(df_train.shape)
print(df_test.shape)

(82580, 30)
(1000, 30)

In [15]:
df_train.nunique()
df_test.nunique()

Unnamed: 0              1000
ID                      1000
Nationality               49
Age                       85
DaysSinceCreation         12
AverageLeadTime          148
LodgingRevenue           319
OtherRevenue             232
BookingsCanceled           1
BookingsNoShowed           1
BookingsCheckedIn          3
PersonsNights             18
RoomNights                12
DaysSinceLastStay         20
DaysSinceFirstStay        19
DistributionChannel        4
MarketSegment              6
SRHighFloor                2
SRLowFloor                 1
SRAccessibleRoom           1
SRMediumFloor              1
SRBathtub                  2
SRShower                   1
SRCrib                     2
SRKingSizeBed              2
SRTwinBed                  2
SRNearElevator             2
SRAwayFromElevator         1
SRNoAlcoholInMiniBar       1
SRQuietRoom                2
dtype: int64

In [16]:
df_train.head()

,Unnamed: 0,ID,Nationality,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,0,1,PRT,51.0,150,45,371.0,105.3,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,PRT,50.0,1095,61,280.0,53.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,3,DEU,31.0,1095,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4,FRA,60.0,1095,93,240.0,60.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,5,FRA,51.0,1095,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df_test.head()

,Unnamed: 0,ID,Nationality,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,82590,82591,SGP,47.0,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,82591,82592,SGP,16.0,11,130,483.48,155.1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,82592,82593,SGP,15.0,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,82593,82594,SGP,12.0,11,0,0.00,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,82594,82595,PRT,46.0,11,0,0.00,0.0,0,0,...,0,0,0,0,1,0,0,0,0,0

Setting the ID column as index

In [18]:
df_train.set_index('ID')
df_test.set_index('ID')

,Unnamed: 0,Nationality,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,BookingsCheckedIn,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
ID,,,,,,,,,,,,,,,,,,,,,
82591,82590,SGP,47.0,11,0,0.00,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82592,82591,SGP,16.0,11,130,483.48,155.1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
82593,82592,SGP,15.0,11,0,0.00,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82594,82593,SGP,12.0,11,0,0.00,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82595,82594,PRT,46.0,11,0,0.00,0.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83586,83585,ITA,54.0,0,0,0.00,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
83587,83586,IRL,47.0,0,109,327.10,277.5,0,0,1,...,0,0,0,0,1,0,0,0,0,0
83588,83587,IRL,53.0,0,0,0.00,0.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
83589,83588,IRL,85.0,0,109,981.30,9.0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
83590,83589,IRL,13.0,0,0,0.00,0.0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

#Data Preparation #

In our data we have various booking status under one ID reference, here we are going to calculate how many times a certain ID number has initiated a booking and store it in TotalBookingInitiated, then calculate the ratio of total initiation with succesful check-in, and use that value as a measure for making further decision.

In [19]:

sum_col_train=df_train['BookingsCanceled']+df_train['BookingsNoShowed']+df_train['BookingsCheckedIn']
sum_col_test=df_test['BookingsCanceled']+df_test['BookingsNoShowed']+df_test['BookingsCheckedIn']

df_train['TotalBookingInitiated']=sum_col_train
df_test['TotalBookingInitiated']=sum_col_test

score_train=df_train['BookingsCheckedIn']/df_train['TotalBookingInitiated']
score_test=df_test['BookingsCheckedIn']/df_test['TotalBookingInitiated']

df_train['BookingScore']=score_train
df_test['BookingScore']=score_test

In [20]:
df_train['BookingScore'].unique()

array([0.75      , 1.        ,        nan, 0.5       , 0.91666667,
       0.7       , 0.66666667, 0.33333333, 0.875     , 0.94285714,
       0.9375    , 0.96666667, 0.90625   , 0.85714286, 0.96153846,
       0.90909091, 0.87878788, 0.69230769, 0.88235294, 0.8125    ,
       0.81818182, 0.8       , 0.96296296, 0.85185185, 0.92307692,
       0.86363636, 0.95238095, 0.72222222, 0.88888889, 0.83333333,
       0.71428571, 0.93333333, 0.        , 0.74074074, 0.73333333,
       0.97142857])

In [21]:
df_train['BookingScore'] = df_train['BookingScore'].replace(np.nan, 0)
df_test['BookingScore'] = df_test['BookingScore'].replace(np.nan, 0)

We have found the ratio of BookingsCheckedIn to TotalBookingInitiated, now using this value we will put a threshold of 0.5. Anything above the threshold we will assign 1 as checkin made, else we will assign 0 as checkin not made.

In [22]:
df_train.loc[df_train['BookingScore'] >0.7,'BookingPrediction'] = 1
df_train.loc[df_train['BookingScore']<=0.7,'BookingPrediction'] = 0
df_test.loc[df_test['BookingScore'] >0.7,'BookingPrediction'] = 1
df_test.loc[df_test['BookingScore']<=0.7,'BookingPrediction'] = 0
 
df_train.head()

,Unnamed: 0,ID,Nationality,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,...,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom,TotalBookingInitiated,BookingScore,BookingPrediction
0,0,1,PRT,51.0,150,45,371.0,105.3,1,0,...,0,0,0,0,0,0,0,4,0.75,1.0
1,1,2,PRT,50.0,1095,61,280.0,53.0,0,0,...,0,0,0,0,0,0,0,1,1.00,1.0
2,2,3,DEU,31.0,1095,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.0
3,3,4,FRA,60.0,1095,93,240.0,60.0,0,0,...,0,0,0,0,0,0,0,1,1.00,1.0
4,4,5,FRA,51.0,1095,0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0.00,0.0

## Correlation map to check correlation between each variable
Initially we lacked a proper target vector, now that we have derived the target vector using the data available to us, we are going to view how the variables available tous are related with each other.

In [23]:
corr=df_train.corr()
plt.figure(figsize = (1,1)) 
corr.style.background_gradient(cmap='coolwarm')

#Dropping extra features:
ID is highly corelated with unnamed index column, lets drop unnamed column, similarly,DaysSinceCreation is highly correlated with DaysSinceLastStay and DaysSinceFirstStay

In [24]:
df_train = df_train.drop(columns = ['Unnamed: 0','DaysSinceLastStay', 'DaysSinceFirstStay'])
df_test = df_test.drop(columns = ['Unnamed: 0','DaysSinceLastStay', 'DaysSinceFirstStay'])

In [25]:
df_train.columns

Index(['ID', 'Nationality', 'Age', 'DaysSinceCreation', 'AverageLeadTime',
       'LodgingRevenue', 'OtherRevenue', 'BookingsCanceled',
       'BookingsNoShowed', 'BookingsCheckedIn', 'PersonsNights', 'RoomNights',
       'DistributionChannel', 'MarketSegment', 'SRHighFloor', 'SRLowFloor',
       'SRAccessibleRoom', 'SRMediumFloor', 'SRBathtub', 'SRShower', 'SRCrib',
       'SRKingSizeBed', 'SRTwinBed', 'SRNearElevator', 'SRAwayFromElevator',
       'SRNoAlcoholInMiniBar', 'SRQuietRoom', 'TotalBookingInitiated',
       'BookingScore', 'BookingPrediction'],
      dtype='object')

Viewing how the remaining data correlates with the target vector:

In [26]:
correlation = df_train.corr()['BookingPrediction'].abs().sort_values(ascending = False)
correlation

BookingPrediction        1.000000
BookingScore             0.999111
BookingsCheckedIn        0.630545
TotalBookingInitiated    0.591821
RoomNights               0.573365
PersonsNights            0.566002
LodgingRevenue           0.444361
ID                       0.426661
AverageLeadTime          0.419892
DaysSinceCreation        0.413857
OtherRevenue             0.327594
Age                      0.194015
SRCrib                   0.057207
SRTwinBed                0.030250
SRHighFloor              0.023833
BookingsCanceled         0.015776
SRKingSizeBed            0.015369
BookingsNoShowed         0.012958
SRQuietRoom              0.008788
SRNoAlcoholInMiniBar     0.006849
SRLowFloor               0.006175
SRAwayFromElevator       0.005799
SRAccessibleRoom         0.005281
SRBathtub                0.005010
SRNearElevator           0.003107
SRMediumFloor            0.002124
SRShower                 0.000493
Name: BookingPrediction, dtype: float64

Dropping those columns which are not effecting the target vector as much, these are unnecessary for out prediction model.

In [27]:
drop_col=['SRHighFloor', 'SRLowFloor',
       'SRAccessibleRoom', 'SRMediumFloor', 'SRBathtub', 'SRShower', 'SRCrib','AverageLeadTime',
       'SRKingSizeBed', 'SRTwinBed', 'SRNearElevator', 'SRAwayFromElevator','TotalBookingInitiated','BookingScore',
       'SRNoAlcoholInMiniBar', 'SRQuietRoom','Age','BookingsCheckedIn','Nationality','ID','BookingsNoShowed','BookingsCanceled']
df_train.drop(drop_col,axis=1,inplace=True)  
df_test.drop(drop_col,axis=1,inplace=True)

In [28]:
df_train.head()
df_test.head()

,DaysSinceCreation,LodgingRevenue,OtherRevenue,PersonsNights,RoomNights,DistributionChannel,MarketSegment,BookingPrediction
0,11,0.00,0.0,0,0,Travel Agent/Operator,Other,0.0
1,11,483.48,155.1,15,5,Travel Agent/Operator,Other,1.0
2,11,0.00,0.0,0,0,Travel Agent/Operator,Other,0.0
3,11,0.00,0.0,0,0,Travel Agent/Operator,Other,0.0
4,11,0.00,0.0,0,0,Travel Agent/Operator,Other,0.0

Separating the categorical columns to perform encoding

In [29]:
cat_cols_train = [col for col in df_train.columns if df_train[col].dtype == 'O']
cat_cols_test = [col for col in df_test.columns if df_test[col].dtype == 'O']
cat_cols_train
cat_cols_test

['DistributionChannel', 'MarketSegment']

In [30]:
cat_df_train = df_train[cat_cols_train]
cat_df_test = df_test[cat_cols_test]
cat_df_train.head()
cat_df_test.head()

     DistributionChannel MarketSegment
0  Travel Agent/Operator         Other
1  Travel Agent/Operator         Other
2  Travel Agent/Operator         Other
3  Travel Agent/Operator         Other
4  Travel Agent/Operator         Other

In [31]:
# printing unique values of categorical column
for col in cat_df_train.columns:
    print(f"{col}: \n{cat_df_train[col].unique()}\n")

DistributionChannel:
['Corporate' 'Travel Agent/Operator' 'Direct' 'Electronic Distribution']

MarketSegment:
['Corporate' 'Travel Agent/Operator' 'Other' 'Direct' 'Complementary'
 'Groups' 'Aviation']

Encoding of the categorical variables

In [32]:
cat_df_train['MarketSegment'] = cat_df_train['MarketSegment'].map({'Direct': 0, 'Corporate': 1, 'Travel Agent/Operator': 2,'Complementary': 3, 'Groups': 5, 'Other': 6, 'Aviation': 7})
cat_df_test['MarketSegment'] = cat_df_test['MarketSegment'].map({'Direct': 0, 'Corporate': 1, 'Travel Agent/Operator': 2,'Complementary': 3, 'Groups': 5, 'Other': 6, 'Aviation': 7})

cat_df_train['DistributionChannel'] = cat_df_train['DistributionChannel'].map({'Direct': 0, 'Corporate': 1, 'Travel Agent/Operator': 2, 'Electronic Distribution': 3})
cat_df_test['DistributionChannel'] = cat_df_test['DistributionChannel'].map({'Direct': 0, 'Corporate': 1, 'Travel Agent/Operator': 2, 'Electronic Distribution': 3})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [33]:
cat_df_train.head()

   DistributionChannel  MarketSegment
0                    1              1
1                    2              2
2                    2              2
3                    2              2
4                    2              2

Separating the numerical variable columns from target vector

In [34]:
num_df_train = df_train.drop(columns = cat_cols_train, axis = 1)
num_df_test = df_test.drop(columns = cat_cols_train, axis = 1)
num_df_train.drop('BookingPrediction', axis = 1, inplace = True)
num_df_test.drop('BookingPrediction', axis = 1, inplace = True)
num_df_train
num_df_test

,DaysSinceCreation,LodgingRevenue,OtherRevenue,PersonsNights,RoomNights
0,11,0.00,0.0,0,0
1,11,483.48,155.1,15,5
2,11,0.00,0.0,0,0
3,11,0.00,0.0,0,0
4,11,0.00,0.0,0,0
...,...,...,...,...,...
995,0,0.00,0.0,0,0
996,0,327.10,277.5,6,3
997,0,0.00,0.0,0,0
998,0,981.30,9.0,6,3
999,0,0.00,0.0,0,0

In [35]:
num_df_train.var()

DaysSinceCreation     96913.477213
LodgingRevenue       139380.521005
OtherRevenue          13109.385149
PersonsNights            20.816472
RoomNights                5.206417
dtype: float64

Normalising the numerical variable , the test and train dataset is normallised separately because the mean will change if we do it together.

In [36]:

num_df_train['DaysSinceCreation'] = np.log(num_df_train['DaysSinceCreation'] + 1)
num_df_test['DaysSinceCreation'] = np.log(num_df_test['DaysSinceCreation'] + 1)

num_df_train['LodgingRevenue'] = np.log(num_df_train['LodgingRevenue'] + 1)
num_df_test['LodgingRevenue'] = np.log(num_df_test['LodgingRevenue'] + 1)

num_df_train['OtherRevenue'] = np.log(num_df_train['OtherRevenue'] + 1)
num_df_test['OtherRevenue'] = np.log(num_df_test['OtherRevenue'] + 1)

num_df_train['PersonsNights'] = np.log(num_df_train['PersonsNights'] + 1)
num_df_test['PersonsNights'] = np.log(num_df_test['PersonsNights'] + 1)

num_df_train['RoomNights'] = np.log(num_df_train['RoomNights'] + 1)
num_df_test['RoomNights'] = np.log(num_df_test['RoomNights'] + 1)

In [37]:
num_df_train.var()

DaysSinceCreation    0.827301
LodgingRevenue       6.350965
OtherRevenue         3.764509
PersonsNights        0.831822
RoomNights           0.440883
dtype: float64

In [38]:
num_df_train.head()

   DaysSinceCreation  LodgingRevenue  OtherRevenue  PersonsNights  RoomNights
0           5.017280        5.918894      4.666265       2.197225    1.791759
1           6.999422        5.638355      3.988984       2.397895    1.791759
2           6.999422        0.000000      0.000000       0.000000    0.000000
3           6.999422        5.484797      4.110874       2.397895    1.791759
4           6.999422        0.000000      0.000000       0.000000    0.000000

Assigning Input and Output variables for further application of model and predictions

In [39]:
X_train= pd.concat([cat_df_train, num_df_train], axis = 1)
X_test= pd.concat([cat_df_test, num_df_test], axis = 1)
y_train=df_train['BookingPrediction']
y_test=df_test['BookingPrediction']

In [40]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape
X_train.head()
y_train.head()

0    1.0
1    1.0
2    0.0
3    1.0
4    0.0
Name: BookingPrediction, dtype: float64

#Model Building#

Logistic  regression

In [41]:
#import logistic regression model
from sklearn.linear_model import LogisticRegression

#Importing metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

acc_lr = accuracy_score(y_test, y_pred_lr)
conf = confusion_matrix(y_test, y_pred_lr)
clf_report = classification_report(y_test, y_pred_lr)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.999
Confusion Matrix :
[[521   0]
 [  1 478]]
Classification Report :
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       521
         1.0       1.00      1.00      1.00       479

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

#Decision Tree Classifier

In [42]:
#import decision tree classifier
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

y_pred_dtc = dtc.predict(X_test)

acc_dtc = accuracy_score(y_test, y_pred_dtc)
conf = confusion_matrix(y_test, y_pred_dtc)
clf_report = classification_report(y_test, y_pred_dtc)

print(f"Accuracy Score of Decision Tree is : {acc_dtc}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Decision Tree is : 0.999
Confusion Matrix :
[[521   0]
 [  1 478]]
Classification Report :
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       521
         1.0       1.00      1.00      1.00       479

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

#ADA Boost Classifier

In [43]:
#Import ada boost classifier
from sklearn.ensemble import AdaBoostClassifier

# Ada Boost Classifier

ada = AdaBoostClassifier(base_estimator = dtc)
ada.fit(X_train, y_train)

y_pred_ada = ada.predict(X_test)

acc_ada = accuracy_score(y_test, y_pred_ada)
conf = confusion_matrix(y_test, y_pred_ada)
clf_report = classification_report(y_test, y_pred_ada)

print(f"Accuracy Score of Ada Boost Classifier is : {acc_ada}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Ada Boost Classifier is : 1.0
Confusion Matrix :
[[521   0]
 [  0 479]]
Classification Report :
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       521
         1.0       1.00      1.00      1.00       479

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

#Gradient Boost Classifier

In [44]:
#Import gradient boosting classifier
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

acc_gb = accuracy_score(y_test, y_pred_gb)
conf = confusion_matrix(y_test, y_pred_gb)
clf_report = classification_report(y_test, y_pred_gb)

print(f"Accuracy Score of Ada Boost Classifier is : {acc_gb}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Ada Boost Classifier is : 1.0
Confusion Matrix :
[[521   0]
 [  0 479]]
Classification Report :
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       521
         1.0       1.00      1.00      1.00       479

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

#CAT Boost Classifier

In [48]:
pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: catboost in /usr/local/lib/python3.7/dist-packages (1.0.6)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.7.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.21.6)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2022.2.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->catboost) (4.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (8.0.1)

In [49]:
#importing Cat  boost classifier
from catboost import CatBoostClassifier

cat = CatBoostClassifier(iterations=100)
cat.fit(X_train, y_train)

y_pred_cat = cat.predict(X_test)

acc_cat = accuracy_score(y_test, y_pred_cat)
conf = confusion_matrix(y_test, y_pred_cat)
clf_report = classification_report(y_test, y_pred_cat)

Learning rate set to 0.5
0:	learn: 0.3152560	total: 97.5ms	remaining: 9.65s
1:	learn: 0.1731438	total: 152ms	remaining: 7.45s
2:	learn: 0.1011555	total: 188ms	remaining: 6.08s
3:	learn: 0.0611832	total: 238ms	remaining: 5.7s
4:	learn: 0.0384503	total: 270ms	remaining: 5.13s
5:	learn: 0.0251939	total: 311ms	remaining: 4.87s
6:	learn: 0.0172009	total: 342ms	remaining: 4.54s
7:	learn: 0.0125578	total: 363ms	remaining: 4.17s
8:	learn: 0.0097576	total: 388ms	remaining: 3.92s
9:	learn: 0.0079122	total: 400ms	remaining: 3.6s
10:	learn: 0.0068583	total: 410ms	remaining: 3.31s
11:	learn: 0.0062524	total: 419ms	remaining: 3.08s
12:	learn: 0.0058844	total: 429ms	remaining: 2.87s
13:	learn: 0.0057345	total: 438ms	remaining: 2.69s
14:	learn: 0.0055907	total: 447ms	remaining: 2.53s
15:	learn: 0.0055543	total: 456ms	remaining: 2.39s
16:	learn: 0.0055302	total: 464ms	remaining: 2.27s
17:	learn: 0.0053889	total: 473ms	remaining: 2.16s
18:	learn: 0.0052749	total: 483ms	remaining: 2.06s
19:	learn: 0.0052338	total: 492ms	remaining: 1.97s
20:	learn: 0.0052083	total: 500ms	remaining: 1.88s
21:	learn: 0.0051916	total: 508ms	remaining: 1.8s
22:	learn: 0.0050182	total: 517ms	remaining: 1.73s
23:	learn: 0.0049588	total: 526ms	remaining: 1.67s
24:	learn: 0.0049405	total: 535ms	remaining: 1.6s
25:	learn: 0.0049243	total: 556ms	remaining: 1.58s
26:	learn: 0.0048962	total: 569ms	remaining: 1.54s
27:	learn: 0.0048721	total: 588ms	remaining: 1.51s
28:	learn: 0.0048544	total: 619ms	remaining: 1.51s
29:	learn: 0.0048190	total: 640ms	remaining: 1.49s
30:	learn: 0.0048095	total: 665ms	remaining: 1.48s
31:	learn: 0.0047141	total: 693ms	remaining: 1.47s
32:	learn: 0.0046714	total: 717ms	remaining: 1.46s
33:	learn: 0.0046411	total: 740ms	remaining: 1.44s
34:	learn: 0.0046188	total: 763ms	remaining: 1.42s
35:	learn: 0.0045794	total: 795ms	remaining: 1.41s
36:	learn: 0.0045704	total: 825ms	remaining: 1.4s
37:	learn: 0.0045552	total: 851ms	remaining: 1.39s
38:	learn: 0.0045478	total: 862ms	remaining: 1.35s
39:	learn: 0.0045404	total: 880ms	remaining: 1.32s
40:	learn: 0.0044896	total: 894ms	remaining: 1.29s
41:	learn: 0.0044763	total: 905ms	remaining: 1.25s
42:	learn: 0.0044636	total: 915ms	remaining: 1.21s
43:	learn: 0.0044559	total: 926ms	remaining: 1.18s
44:	learn: 0.0044471	total: 938ms	remaining: 1.15s
45:	learn: 0.0044326	total: 956ms	remaining: 1.12s
46:	learn: 0.0044240	total: 978ms	remaining: 1.1s
47:	learn: 0.0043961	total: 1.01s	remaining: 1.09s
48:	learn: 0.0043890	total: 1.04s	remaining: 1.08s
49:	learn: 0.0043747	total: 1.06s	remaining: 1.06s
50:	learn: 0.0043013	total: 1.09s	remaining: 1.05s
51:	learn: 0.0042832	total: 1.12s	remaining: 1.03s
52:	learn: 0.0042775	total: 1.14s	remaining: 1.01s
53:	learn: 0.0042726	total: 1.17s	remaining: 997ms
54:	learn: 0.0042684	total: 1.21s	remaining: 990ms
55:	learn: 0.0042642	total: 1.23s	remaining: 970ms
56:	learn: 0.0042589	total: 1.25s	remaining: 941ms
57:	learn: 0.0042554	total: 1.26s	remaining: 910ms
58:	learn: 0.0042466	total: 1.26s	remaining: 879ms
59:	learn: 0.0042297	total: 1.28s	remaining: 852ms
60:	learn: 0.0042291	total: 1.29s	remaining: 823ms
61:	learn: 0.0042086	total: 1.29s	remaining: 794ms
62:	learn: 0.0041721	total: 1.3s	remaining: 766ms
63:	learn: 0.0041645	total: 1.31s	remaining: 738ms
64:	learn: 0.0041530	total: 1.32s	remaining: 712ms
65:	learn: 0.0041470	total: 1.33s	remaining: 686ms
66:	learn: 0.0041405	total: 1.34s	remaining: 660ms
67:	learn: 0.0041352	total: 1.35s	remaining: 634ms
68:	learn: 0.0041291	total: 1.36s	remaining: 609ms
69:	learn: 0.0041224	total: 1.36s	remaining: 585ms
70:	learn: 0.0041156	total: 1.37s	remaining: 561ms
71:	learn: 0.0041100	total: 1.38s	remaining: 537ms
72:	learn: 0.0041075	total: 1.39s	remaining: 514ms
73:	learn: 0.0041036	total: 1.4s	remaining: 492ms
74:	learn: 0.0040920	total: 1.41s	remaining: 471ms
75:	learn: 0.0040794	total: 1.44s	remaining: 454ms
76:	learn: 0.0040732	total: 1.47s	remaining: 439ms
77:	learn: 0.0040649	total: 1.49s	remaining: 419ms
78:	learn: 0.0040585	total: 1.5s	remaining: 400ms
79:	learn: 0.0040370	total: 1.52s	remaining: 380ms
80:	learn: 0.0040293	total: 1.53s	remaining: 360ms
81:	learn: 0.0040242	total: 1.56s	remaining: 342ms
82:	learn: 0.0040174	total: 1.59s	remaining: 326ms
83:	learn: 0.0040132	total: 1.61s	remaining: 307ms
84:	learn: 0.0040084	total: 1.63s	remaining: 287ms
85:	learn: 0.0039954	total: 1.64s	remaining: 267ms
86:	learn: 0.0039914	total: 1.65s	remaining: 247ms
87:	learn: 0.0039875	total: 1.66s	remaining: 227ms
88:	learn: 0.0039823	total: 1.67s	remaining: 207ms
89:	learn: 0.0039793	total: 1.68s	remaining: 187ms
90:	learn: 0.0039769	total: 1.7s	remaining: 168ms
91:	learn: 0.0039572	total: 1.71s	remaining: 148ms
92:	learn: 0.0039524	total: 1.72s	remaining: 129ms
93:	learn: 0.0039494	total: 1.74s	remaining: 111ms
94:	learn: 0.0039471	total: 1.77s	remaining: 93.1ms
95:	learn: 0.0039444	total: 1.8s	remaining: 74.9ms
96:	learn: 0.0039423	total: 1.82s	remaining: 56.2ms
97:	learn: 0.0039396	total: 1.83s	remaining: 37.3ms
98:	learn: 0.0039371	total: 1.84s	remaining: 18.5ms
99:	learn: 0.0039144	total: 1.84s	remaining: 0us

In [50]:
print(f"Accuracy Score of Ada Boost Classifier is : {acc_cat}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Ada Boost Classifier is : 1.0
Confusion Matrix :
[[521   0]
 [  0 479]]
Classification Report :
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       521
         1.0       1.00      1.00      1.00       479

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

#ANN(Artificial Neural Network)

In [51]:
from tensorflow.keras.utils import to_categorical

X1 = pd.concat([cat_df_train, num_df_train], axis = 1)
X2 = pd.concat([cat_df_test, num_df_test], axis = 1)
y1 = to_categorical(df_train['BookingPrediction'])
y2 = to_categorical(df_test['BookingPrediction'])

In [52]:
# splitting data into training set and test set

X_train, X_test, y_train, y_test = X1,X2,y1,y2

In [53]:
X_train.shape

(82580, 7)

In [54]:
# from keras import optimizers
# sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

AttributeError: ignored

In [55]:
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras import optimizers


num_epochs = 10
x_shape = (None, X_train.shape[-1])

model  = Sequential()
model.add(Dense(50, activation = 'relu', input_shape = x_shape))
model.add(Dense(50, activation = 'relu'))
model.add(Dense(2, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model_history = model.fit(X_train, y_train, validation_data = (X_test, y_test),epochs = num_epochs)

Epoch 1/10

WARNING:tensorflow:Model was constructed with shape (None, None, 7) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 7), dtype=tf.float32, name='dense_input'), name='dense_input', description="created by layer 'dense_input'"), but it was called on an input with incompatible shape (None, 7).
WARNING:tensorflow:Model was constructed with shape (None, None, 7) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 7), dtype=tf.float32, name='dense_input'), name='dense_input', description="created by layer 'dense_input'"), but it was called on an input with incompatible shape (None, 7).

2579/2581 [============================>.] - ETA: 0s - loss: 0.0152 - accuracy: 0.9972

WARNING:tensorflow:Model was constructed with shape (None, None, 7) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, 7), dtype=tf.float32, name='dense_input'), name='dense_input', description="created by layer 'dense_input'"), but it was called on an input with incompatible shape (None, 7).

2581/2581 [==============================] - 6s 2ms/step - loss: 0.0152 - accuracy: 0.9972 - val_loss: 0.0134 - val_accuracy: 1.0000
Epoch 2/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0073 - accuracy: 0.9990 - val_loss: 0.0031 - val_accuracy: 1.0000
Epoch 3/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0070 - accuracy: 0.9990 - val_loss: 0.0018 - val_accuracy: 1.0000
Epoch 4/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0068 - accuracy: 0.9991 - val_loss: 0.0017 - val_accuracy: 1.0000
Epoch 5/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0067 - accuracy: 0.9991 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 6/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0064 - accuracy: 0.9991 - val_loss: 0.0018 - val_accuracy: 1.0000
Epoch 7/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0062 - accuracy: 0.9991 - val_loss: 0.0018 - val_accuracy: 1.0000
Epoch 8/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0061 - accuracy: 0.9991 - val_loss: 0.0025 - val_accuracy: 1.0000
Epoch 9/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0059 - accuracy: 0.9991 - val_loss: 0.0012 - val_accuracy: 1.0000
Epoch 10/10
2581/2581 [==============================] - 5s 2ms/step - loss: 0.0059 - accuracy: 0.9991 - val_loss: 0.0018 - val_accuracy: 1.0000

In [56]:
import plotly.express as px

plt.figure(figsize = (12, 6))

train_loss = model_history.history['loss']
val_loss = model_history.history['val_loss'] 
epoch = range(1, num_epochs+1)

loss = pd.DataFrame({'train_loss' : train_loss, 'val_loss' : val_loss})

px.line(data_frame = loss, x = epoch, y = ['val_loss', 'train_loss'], title = 'Training and Validation Loss',
        template = 'plotly_dark')

In [57]:
plt.figure(figsize = (12, 6))

train_acc = model_history.history['accuracy']
val_acc = model_history.history['val_accuracy'] 
epoch = range(1, num_epochs+1)


accuracy = pd.DataFrame({'train_acc' : train_acc, 'val_acc' : val_acc})

px.line(data_frame = accuracy, x = epoch, y = ['val_acc', 'train_acc'], title = 'Training and Validation Accuracy',
        template = 'plotly_dark')

In [58]:
acc_ann = model.evaluate(X_test, y_test)[1]

print(f'Accuracy of model is {acc_ann}')

32/32 [==============================] - 0s 1ms/step - loss: 0.0018 - accuracy: 1.0000
Accuracy of model is 1.0

#Model comparison

In [60]:
models = pd.DataFrame({
    'Model' : ['Logistic Regression', 'Decision Tree Classifier','Ada Boost Classifier',
             'Gradient Boosting Classifier', 'Cat Boost', 'ANN'],
    'Score' : [acc_lr, acc_dtc, acc_ada, acc_gb, acc_cat, acc_ann]
})


models.sort_values(by = 'Score', ascending = False)

                          Model  Score
2          Ada Boost Classifier  1.000
3  Gradient Boosting Classifier  1.000
4                     Cat Boost  1.000
5                           ANN  1.000
0           Logistic Regression  0.999
1      Decision Tree Classifier  0.999

In [61]:
px.bar(data_frame = models, x = 'Score', y = 'Model', color = 'Score', template = 'plotly_dark', title = 'Models Comparison')